version: "3.3"
services:
  db:
    image: 'postgres:10-alpine'
    container_name: 'postgresnew'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4321
      - POSTGRES_DB=twr
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build: ./frontendtwr
    ports:
      - 80:80
    volumes: 
      - ./frontendtwr:/app
      - /app/node_modules/
  backend: 
    build: ./backendtwr
    ports: 
      - 8080:8080
    volumes:
      - ./backendtwr:/app
      - /app/node_modules/
    env_file:
      - .env
volumes: 
  pgdata:
