version: "3"
services:
  frontend:
    build: frontendtwr/.
    env_file:
      - prod-env
    networks:
      - myNetwork
  backend: 
    build: backendtwr/.
    env_file:
      - prod-env
    networks:
      - myNetwork
networks:
  myNetwork:
     external: true
