version: "3.3"
services:
  db:
    image: 'postgres:10-alpine'
    container_name: 'postgresnew'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    container_name: 'frontend'
    build: 
      context: ./frontendtwr
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4200
    volumes: 
      - ./frontendtwr:/app
      - /app/node_modules/
  backend: 
    container_name: 'backend'
    build: 
      context: ./backendtwr
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    volumes:
      - ./backendtwr:/app
      - /app/node_modules/
    env_file:
      - .env
volumes: 
  pgdata:
