version: "3"
services:
  frontend:
    build: ./frontendtwr
    ports:
      - 80:4200
    links: 
      - backend
    volumes: 
      - ./frontendtwr:/app
      - /app/node_modules/
    depends_on: 
      - backend
  backend: 
    build: ./backendtwr
    ports: 
      - 4000:8080
    volumes:
      - ./backendtwr:/app
      - /app/node_modules/
    env_file:
      - .env
  networks:
    default:
      external:
        name: myNetwork

