# base image
FROM node:12.2.0
# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app
RUN npm install

# add app
COPY . .

# start app
CMD ng serve --host 0.0.0.0
